
version: 2

sources:
  - name: taxi_data
    description: "nyc taxi trip data - app data"
    database: taxi
    schema: raw
    tables:
      - name: yellow_tripdata
        description: >
          nyc yellow taxi trip data
          detailed data description: https://www.nyc.gov/assets/tlc/downloads/pdf/data_dictionary_trip_records_yellow.pdf

        columns:
          - name: VendorID
            data_type: Integer
            description: >
              A code indicating the TPEP provider that provided the record. 
              1= Creative Mobile Technologies, LLC; 2= VeriFone Inc.

          - name: tpep_pickup_datetime
            data_type: timestamp
            description: >
              The date and time when the meter was engaged. 

          - name: tpep_dropoff_datetime
            data_type: timestamp
            description: >
              The date and time when the meter was disengaged. 
                          
          - name: passenger_count
            data_type: Float
            description: >
              The number of passengers in the vehicle.
              This is a driver-entered value

          - name: trip_distance
            data_type: Float
            description: >
              The elapsed trip distance in miles reported by the taximeter

          - name: RatecodeID
            data_type: Float
            description: >
              The final rate code in effect at the end of the trip.
              1 = Standard rate
              2 = JFK
              3 = Newark
              4 = Nassau or Westchester
              5 = Negotiated fare
              6 = Group ride

          - name: store_and_fwd_flag
            data_type: Text
            description: >
              This flag indicates whether the trip record was held in vehicle
              memory before sending to the vendor, aka “store and forward,”
              because the vehicle did not have a connection to the server.
              Y= store and forward trip
              N= not a store and forward trip
                          
          - name: "PULocationID"
            data_type: Integer
            description: >
              TLC Taxi Zone in which the taximeter was engaged
              
          - name: "DOLocationID"
            data_type: Integer
            description: >
              TLC Taxi Zone in which the taximeter was disengaged


          - name: payment_type
            data_type: Integer
            description: >
              A numeric code signifying how the passenger paid for the trip.
              1 = Credit card
              2 = Cash
              3 = No charge
              4 = Dispute
              5 = Unknown
              6 = Voided trip

          - name: fare_amount
            data_type: Float
            description: >
              The time-and-distance fare calculated by the meter.
                          
          - name: extra
            data_type: Float
            description: >
              Miscellaneous extras and surcharges. Currently, this only includes
              the $0.50 and $1 rush hour and overnight charges.
                          
          - name: mta_tax
            data_type: Float
            description: >
              $0.50 MTA tax that is automatically triggered based on the metered
              rate in use.

          - name: tip_amount
            data_type: Float   
            description: >
              Tip amount – This field is automatically populated for credit card
              tips. Cash tips are not included.

          - name: tolls_amount
            data_type: Float
            description: >
              Total amount of all tolls paid in trip.

          - name: improvement_surcharge
            data_type: Float
            description: >
              $0.30 improvement surcharge assessed trips at the flag drop. The
              improvement surcharge began being levied in 2015.            
                      
          - name: total_amount
            data_type: Float        
            description: >
              The total amount charged to passengers. Does not include cash tips                          

          - name: congestion_surcharge
            data_type: Float
            description: >
               Total amount collected in trip for NYS congestion surcharge.

          - name: airport_fee
            data_type: Text
            description: >
              $1.25 for pick up only at LaGuardia and John F. Kennedy Airports


exposures:
  ###   sales revenue and distribution
  - name: daily_taxi_revenue
    type: dashboard
    depends_on:
      - ref('marts_daily_taxi_revenue')
    owner:
      name: charles

  - name: daily_received_amount_distribution
    type: dashboard
    description: >
      received amount (paid by customer) breakdown details
    depends_on:
      - ref('marts_daily_taxi_received_amt_distrib')
    owner:
      name: charles

  ###   business opportunity
  - name: daily_popular_pickup_dropoff_locations
    type: dashboard
    maturity: high
    description: >
      popular (pickup / dropoff) locations per date
    depends_on:
      - ref('marts_daily_popular_pickup_dropoff_locations')
    owner:
      name: charles

  ###   revenue and opportunity consolidation
  - name: daily_taxi_revenue_and_opportunity_consol
    type: dashboard
    maturity: high
    description: >
      sales revenue and business opportunity per date
    depends_on:
      - ref('marts_daily_taxi_revenue_and_opportunity_consol')
    owner:
      name: charles
